sonar.projectKey=Zywite_Melody_box
sonar.projectName=MelodyBox
sonar.projectVersion=1.0.0
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.sources=src/app
sonar.tests=src/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/tests/**,**/__pycache__/**,**/venv/**,**/node_modules/**,**/.*/**
sonar.host.url=https://sonarqube.inf.uct.cl
